### ISSUE TITLE
Audit & Refactor Angular-Related Documentation / Guides 

### ISSUE THREAD

**Issue by medelman17** [aws-amplify/docs#3287]
Based on recent feedback/issue submission, our Angular-related documentation/guides need some TLC. This epic serves to organize the work needed to address the above. 

Linked Issues for Non-ZenHub Users:

- [x] https://github.com/aws-amplify/docs/issues/2918 - [Feedback]the angular code doesn't compile
- [ ] https://github.com/aws-amplify/docs/issues/3064 - [Feedback] Missing Step on Getting Started Tutorial
- [x] https://github.com/aws-amplify/docs/issues/3114 - amplify auth turorial - for angular - not complete and erroring.
- [x] https://github.com/aws-amplify/docs/issues/3140 - [Feedback]Multiple errors in the meat of the tutorial - giving up
- [ ] https://github.com/aws-amplify/docs/issues/3246 - Amplify is not compatible with (Ionic Angular 10) anymore (Android)
- [x] https://github.com/aws-amplify/docs/issues/3286 - [Feedback] Authentication Instructions not working
- [x] https://github.com/aws-amplify/docs/issues/3376 - [Feedback]Tons of errors in Angular 12 app

**Comment by mauerbac** [comment]
Ping - @sammartinez @wlee221 @Milan-Shah
